project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "NYC Marathon 2024 Analysis"
  author:
    - Sara Carter (sec2238)
    - Andrea Gomez Lloret (ag5008)
  repo-url: https://github.com/agomezlloret/edav_final_proj.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: morph
    code-fold: true


